### ISSUE TITLE
List the members of the batch (read OnbardingBatch contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch3.buidlguidl.com#3]
Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract <add here>
- Each builder should link to their personal profile <add here>

**Comment by Ahmedborwin** [comment]
Hey - i will give this issue a go!

**Comment by Ahmedborwin** [comment]
Hey - making progress on this issue. Pulling the builders by reading the event history (took me a minute to figure this out!)
I want to also pull the ens name for the builder. Trying to figure out how to correctly use the useEnsName hook on the list of builder address'. Will update later today and hopefully push later this afternoon.

**Comment by Ahmedborwin** [comment]
Hey, finished with this issue. There is an error on console that Contract is not found first time useScaffoldEventHistory is called. Is this something i should worry about? Ideally, i would find a way to only call the hook once the contract is truthy but not sure how to..
