### ISSUE TITLE
Tweak the main page

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch3.buidlguidl.com#6]
## Goal

Discuss with your peers what you would like the homepage to show! It can be a good opportunity to tweak the app colors/layout etc.

As in [pervious issue](https://github.com/BuidlGuidl/batch3.buidlguidl.com/issues/8), keep it simple (no big images, external assets, etc)

This can be an ongoing issue while you all keep implementing things.

**Comment by Ahmedborwin** [comment]
Hey guys - any ideas on what you would like to do for this issue? Anyone have a colour scheme in mind?

**Comment by carletex** [comment]
You can check what batch2 did: https://batch2.buidlguidl.com/ or https://batch1.buidlguidl.com/ (with DALL-E image :D)

This is just an issue to have a more customized homepage for your batch.

**Comment by carletex** [comment]
Fixed on #17
